In [ ]:
import pandas as pd

In [ ]:
npr=pd.read_csv("/content/drive/MyDrive/Copy of npr (1).xls")

In [ ]:
npr.head()

                                             Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

## **Preprocessing**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [ ]:
dtm = cv.fit_transform(npr['Article'])

In [ ]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3033388 stored elements and shape (11992, 54777)>

# **LDA**

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation

In [ ]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [ ]:
LDA.fit(dtm) # this can take a while, we are dealing with a large amount of documents

LatentDirichletAllocation(n_components=7, random_state=42)

**showing stored words**

In [ ]:
import random

In [ ]:
for i in range(10):
  random_word_id=random.randint(0,54776)
  print(cv.get_feature_names_out()[random_word_id])

antiseptic
infuriate
mohamed
hoping
mortgages
khizr
indolent
denting
cherished
merck

In [ ]:
len(LDA.components_)

7

In [ ]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [ ]:
len(LDA.components_[0])

54777

In [ ]:

single_topic=LDA.components_[0]

In [ ]:
# return the indicaes
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [ ]:
single_topic[18302]

np.float64(0.14285714309286987)

In [ ]:
single_topic[42993]

np.float64(6247.245510521074)

In [ ]:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [ ]:
top_word_indices=single_topic.argsort()[-10:]

In [ ]:
for index in top_word_indices:
  print(cv.get_feature_names_out()[index])

new
percent
government
company
million
care
people
health
said
says

In [ ]:
for index,topic in enumerate(LDA.components_):
  print(f"THE TOP 15 WORDS FOR TOPIC #{index}")
  print([cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
  print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


THE TOP 15 WORDS FOR TOPIC #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


THE TOP 15 WORDS FOR TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', 'just', 'like']


THE TOP 15 WORDS FOR TOPIC #6
['student', 'years', 'data', 'science', 'university', 'people', 'time', 'schools', 'just', 'education', 'new', 'like', 'students', 'school', 'says']

**attaching discoverd topic label to original articals**

In [ ]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3033388 stored elements and shape (11992, 54777)>

In [ ]:
dtm.shape

(11992, 54777)

In [ ]:
len(npr)

11992

In [ ]:
topic_results=LDA.transform(dtm)

In [ ]:
topic_results.shape

(11992, 7)

In [ ]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [ ]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [ ]:
topic_results[0].argmax()

np.int64(1)

combining with oridinal  data

In [ ]:
npr.head()

                                             Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [ ]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0])

In [ ]:
npr["Topic"]=topic_results.argmax(axis=1)

In [ ]:
npr.head(10)

                                             Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      2
5  I did not want to join yoga class. I hated tho...      3
6  With a   who has publicly supported the debunk...      3
7  I was standing by the airport exit, debating w...      2
8  If movies were trying to be more realistic, pe...      3
9  Eighteen years ago, on New Year’s Eve, David F...      2